(define (sum_max a b c)
    (define average (/ (+ a b c) 3))
    (cond ((< a average) (+ b c))
          ((< b average) (+ a c))
          ((< c average) (+ a b))
          (else a) 
    )
)
(sum_max 1 2 3)
